
include ../make/makefile_defines.mk

LIB1_SOURCES=fibonacci.cc
LIB1=fibonacci

BIN1_SOURCES=lambda.cc
BIN1=lambda
BIN1_LIBS=fibonacci

BIN2_SOURCES=variadic.cc
BIN2=variadic





include ../make/makefile_rules.mk
include ../make/makefile_targets.mk


