
include ../make/makefile_defines.mk


HEADER_PREFIX=fibonacci
HEADERS = fibonacci/fibonacci.h


LIB1_SOURCES=fibonacci.cc
LIB1=fibonacci

BIN1_SOURCES=lambda.cc
BIN1=lambda
BIN1_LIBS=fibonacci

BIN2_SOURCES=variadic.cc
BIN2=variadic


BIN3_SOURCES=io.cc
BIN3=io


BIN4_SOURCES=shm.cc
BIN4=shm
BIN4_LIBS=rt



BIN4_SOURCES=probe.cc
BIN4=probe

BIN5_SOURCES=probe_reader.cc
BIN5=probe_reader


BIN6_SOURCES=probe_test.cc
BIN6=probe_test






include ../make/makefile_rules.mk
include ../make/makefile_targets.mk


